input:
  prodjlink:
    interface: "eth0"
    port: 50001

output:
  midi:
    enabled: true
    device: "/dev/ttyAMA0"
    baud_rate: 31250
    ppqn: 24

  control_chain:
    enabled: true
    device: "/dev/ttyUSB0"
    baud_rate: 115200
    gpio_de_pin: 27

logging:
  level: "INFO"
